create table subscription (id integer generated by default as identity (start with 1), plan varchar(255), status varchar(255), payment_method varchar(255), person_id integer, primary key (id));
create table person (id integer generated by default as identity (start with 1), first_name varchar(255), last_name varchar(255), primary key (id));
alter table subscription add constraint FK81ihijcn1kdfwffke0c0sjqeb foreign key (person_id) references person;
